; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Dec 13 2018 20:04:59 GMT+0000 (Greenwich Mean Time)
M561                ; clear any bed transform
M98 Pdeployprobe.g  ; deploy mechanical Z probe
G29                 ; probe the bed and enable compensation
M98 Pretractprobe.g ; retract mechanical Z probe


