; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Dec 13 2018 20:04:59 GMT+0000 (Greenwich Mean Time)
; insert codes for retracting the Z probe here

M280 P3 S90 I1
