; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Dec 13 2018 20:04:59 GMT+0000 (Greenwich Mean Time)

